Discourse headers update
herpaderpaldent/seat-discourse pull request #26
Opened 2020-04-14 23:05 UTC by MichaelErmer

This addresses Discourse latest api changes: https://meta.discourse.org/t/discourse-api-documentation/22706/1

> On April 6th, 2020 we dropped support for all non-HTTP header based authentication (excluding some rss, mail-receiver, and ics routes). This means that API requests that have an api_key and api_username in the query params or in the HTTP body of the request will soon stop working. Please see the example cURL request below for how to update your API requests to use the HTTP headers for authentication.

2020-04-15 03:09 UTC, herpaderpaldent commented
Have you locally tested it? 
Cause i dont have a discourse running atm to test it

2020-04-15 06:00 UTC, herpaderpaldent commented
@MichaelErmer would you be able to make style.ci happy? 

https://github.com/herpaderpaldent/seat-discourse/blob/0910264729e48fbe1dd2399777601aed0712be5d/.styleci.yml#L11
Should be `psr2_braces`

2020-04-16 08:10 UTC, herpaderpaldent commented
I am sorry, style.ci changes are try and error stuff ... would you allow me to edit this PR als maintainer so i shall do it for you? https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests 

i believe all that is needed is removing `- length_ordered_imports` but /shrug never certain until style.ci is complaining. 

Other then that: you have this version running and its working?

2020-04-16 08:11 UTC, herpaderpaldent commented on .styleci.yml
>  - length_ordered_imports
This appears still to be a problem

2020-04-16 08:11 UTC, herpaderpaldent requested changes
Style.ci is still not happy

2020-04-16 08:19 UTC, MichaelErmer commented
The headers also need to be changed to dash from underscore.

2020-04-16 08:43 UTC, MichaelErmer commented
Yes please, the changes are functional now.Am 16.04.2020 10:10 schrieb Herpaderp Aldent <notifications@github.com>:
I am sorry, style.ci changes are try and error stuff ... would you allow me to edit this PR als maintainer so i shall do it for you? https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests
i believe all that is needed is removing - length_ordered_imports but /shrug never certain until style.ci is complaining.
Other then that: you have this version running and its working?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-16 08:52 UTC, 5pitf1re commented
It seems to be complaining about a styleci config that was already there.

2020-04-16 13:04 UTC, 5pitf1re commented
This makes even lil baby Jesus sad.

2020-04-16 15:02 UTC, herpaderpaldent commented
@5pitf1re now that is a finding https://github.styleci.io/analyses/x0JKDb?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2020-04-16 16:10 UTC, 5pitf1re commented
I'm aware, I just don't understand what it thinks that the problem is. Maybe it is super obvious but I'm not a PHP guy.

2020-04-16 16:28 UTC, 5pitf1re commented
(┛◉Д◉)┛彡┻━┻

2020-04-16 19:07 UTC, herpaderpaldent commented
You got two options. Either let style ci create a pull request for you, follow the cross for that or let me edith the Pull request as descriped here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Thank you for your support here anyway

2020-04-16 19:54 UTC, MichaelErmer commented
i cant set that option, as the branch does not belong to me @5pitf1re please create a new PR, I'll close this one...

2020-04-16 19:54 UTC, closed without merging